# Generated by Django 4.1.3 on 2022-12-13 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='album_images')),
                ('slug', models.SlugField(blank=True, max_length=400, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MusAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_music', to='album.album')),
                ('musics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_music', to='music.music')),
            ],
        ),
        migrations.CreateModel(
            name='LikeAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_likes', to='album.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
