# Generated by Django 4.1.3 on 2022-12-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(blank=True, default='satanael2.png', upload_to='music_images'),
        ),
    ]
