# Generated by Django 4.1.3 on 2022-12-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='artist',
            new_name='user',
        ),
    ]
