# Generated by Django 4.1.3 on 2022-12-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likemusic',
            old_name='like_album',
            new_name='like_music',
        ),
    ]
