# Generated by Django 4.1.3 on 2022-12-23 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_rename_artist_music_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('album', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='satanael2.png', upload_to='playlist_images')),
                ('slug', models.SlugField(blank=True, max_length=400, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MusPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_music', to='music.music')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_music', to='playlist.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_music', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
